# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\test.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseTest(HttpRunner):

    config = Config("testcase description")

    teststeps = [
        Step(
            RunRequest("/test")
            .get("http://localhost:5000/test")
            .with_params(**{"a": "${get_random()}", "b": "${get_random_str()}"})
            .with_headers(
                **{
                    "Sec-Fetch-Dest": "document",
                    "Sec-Fetch-Mode": "navigate",
                    "Sec-Fetch-Site": "none",
                    "Sec-Fetch-User": "?1",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0",
                    "sec-ch-ua": '"Not_A Brand";v="8", "Chromium";v="120", "Microsoft Edge";v="120"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-ch-ua-platform": '"Windows"',
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.error_message", "success")
            .assert_equal("body.reference", "111")
            .assert_equal("body.error_code", "0")
        ),
    ]


if __name__ == "__main__":
    TestCaseTest().test_start()
